### PR TITLE
only attempt to replace captures in utf8-like data

### PR DESCRIPTION
**Pull request by tarobomb**
binary data
hides among UTF-8;
once captured, frozen

### CODE REVIEW

**Comment by mrak** [comment]
Is it more useful to determine that the data is _not_ binary? This would allow for things like UTF-16 and the like

**Comment by tarobomb** [comment]
I like the idea of supporting other text encodings for capture replacement. It’d take another config property to specify the encoding, I guess. Possible future enhancement?

This patch just lets stubby serve data that isn’t UTF-8 text, including text in UTF-16 and other encodings, which has been getting mangled by parameterless `value.toString()`.

**Comment by ds0001** [comment]
@mrak This PR fix would help in a project I am working on. When would you think it would be possible to review this? Many thanks.

**Comment by mrak** [comment]
I was under the impression that @tarobomb and @apchamberlain were consolidating some of their PRs for a more flexible solution. There are still some concerns about only UTF-8 or binary being considered

**Comment by tarobomb** [comment]
OK, cool. So as I see it, if the user wants Stubby to replace captures in a file or buffer, then Stubby will need to know what character encoding to use. Currently it assumes everything is UTF-8, so UTF-16 and other text encodings are getting mangled.

How about if we added a new key to the endpoint config, something like `response.encoding`? Setting this to one of the encodings accepted by [`buf.toString(encoding)`](https://nodejs.org/api/buffer.html#buffer_buf_tostring_encoding_start_end) would tell Stubby how to interpret `file` (or the Buffer given as `body`) for capture replacement, and cause Stubby to emit the result with the same encoding. If set to the special value `"none"`, Stubby wouldn’t attempt capture replacement at all.

By default, Stubby would try to decode `file` as UTF-8 and, failing that, fall back to not replacing captures—same behavior as in this PR.

@mrak: If you like this idea, I’m willing to work on the implementation, though it might be a while before I can get around to it. What do you think?

**Comment by mrak** [comment]
I like the idea of `request.encoding` and `response.encoding`, defaulting to `utf8` and allowing things like `binary`. My original thought was to use the headers provided in the HTTP request/response, but they may not always be there (or the user is trying to emulate an API that does not specify them).

Keep in mind that [JavaScript has a Unicode problem](https://mathiasbynens.be/notes/javascript-unicode), and that things like [punycode](https://mathiasbynens.be/notes/javascript-unicode) attempt to alleviate them.

This is part of why this was put off until now. Encoding is a very serious game to get right.

I think to correct this bug:

1. Determine if it is `binary`.
    * `if binary` - skip applying caputes
    * `else` - carry on as normal (assumes `utf8`)
2. Later, in another PR, perhaps allow `request.encoding` and `response.encoding` for any buffer operations.

**Comment by tarobomb** [comment]
@mrak: Yep, step 1 there is basically what this PR does. If the buffer’s decodable as UTF-8, we assume it’s meant to be UTF-8 text and not binary—an imperfect test, but one that [works in almost all cases](https://en.wikipedia.org/wiki/Charset_detection), and I think it’s the best we can do without adding `response.encoding` as described above (step 2). I’ll be happy to work on that enhancement, but it will be at least a few more weeks before I have the time.

This PR won’t replace captures in UTF-16, but the current release version of stubby can’t serve UTF-16 at all, so it’s still a bit of an improvement. This is really just a stopgap to keep stubby from mangling binary, UTF-16, UTF-32, and anything else that isn’t pure UTF-8 text.

**Comment by mrak** [comment]
It was not lost on me that you used a kaiku for the PR text

**Pull request merged**
